# Generated by Django 4.2.7 on 2025-09-25 01:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStation',
            fields=[
                ('station_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Estación de usuario',
                'verbose_name_plural': 'Estaciones de usuarios',
                'db_table': 'user_stations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StationData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('temperature_aht20', models.FloatField(blank=True, null=True)),
                ('humidity_aht20', models.FloatField(blank=True, null=True)),
                ('temperature_bmp280', models.FloatField(blank=True, null=True)),
                ('pressure_bmp280', models.FloatField(blank=True, null=True)),
                ('voltage_mq2', models.FloatField(blank=True, null=True)),
                ('digital_mq2', models.BooleanField(blank=True, null=True)),
                ('voltage_mq135', models.FloatField(blank=True, null=True)),
                ('digital_mq135', models.BooleanField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('station', models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.CASCADE, to='stations.userstation')),
            ],
            options={
                'verbose_name': 'Dato de estación',
                'verbose_name_plural': 'Datos de estaciones',
                'db_table': 'station_data',
                'ordering': ['-timestamp'],
            },
        ),
    ]
